version: "3.9"

services:
  app:
    build:
      context: .
#    ports:
#      - "5678:8080"
    volumes:
      - ./backend:/app
    restart: on-failure
    command: >
      sh -c "/wait-for-it.sh mongodb:27017 -- java -jar app.jar"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: on-failure
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=java
      - MONGO_INITDB_ROOT_USERNAME=tanya
      - MONGO_INITDB_ROOT_PASSWORD=tanya
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf